import "./globals.css";

export const metadata = {
	title: "3D-chatbot",
	description: "Generated by Divyanshu",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body style={{ backgroundColor: 'white' }}>{children}</body>
		</html>
	);
	
}
